version: '3'
services:
  redis:
    image: 'redis'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
  python-daemon:
    build: './python-daemon'
    env_file: '.env'
  rboit-back:
    build: './rboit-back'
    environment:
      PYTHON_DAEMON: 'http://python-daemon/'
      REDIS_URL: 'redis://redis/'
      DEVICE_CACHE_MAX_AGE: '2500'
      DEVICE_HISTORY_LENGTH: '86400000'  # 24 hours
      DEVICE_HISTORY_INTERVAL: '5000'
    ports:
    - '8081:80'  # Only neededfor local testing
  rboit-front:
    build: './rboit-front'
    ports:
    - '8080:80'
