version: '3'

services:
  redis:
    image: 'redis'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
    - 'redis-data:/data'
    command: 'redis-server --save 5 1 --loglevel warning'

  python-daemon:
    build: './python-daemon'
    env_file: '.env'
    ports:
    - '8082:80'  # Only needed for development
    devices:
    - '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A10MONL8-if00-port0'

  govee-bluetooth-daemon:
    build: './govee-bluetooth-daemon'
    environment:
      PORT: '8069'
    network_mode: host  # Needed for bluetooth
    privileged: true  # Needed for bluetooth

  rboit-back:
    build: './rboit-back'
    env_file: '.env'
    environment:
      TZ: 'Europe/Amsterdam'
      PYTHON_DAEMON: 'http://python-daemon/'
      REDIS_URL: 'redis://redis/'
      DEVICE_CACHE_MAX_AGE: '1900'
      DEVICE_HISTORY_LENGTH: '86400000'  # 24 hours
      DEVICE_HISTORY_INTERVAL: '15000'
      CLIENT_HISTORY_INTERVAL: '2000'
      STORE_HISTORY: 'true'
    ports:
    - '8081:80'  # Only needed for development

  rboit-front:
    build: './rboit-front'
    ports:
    - '8080:80'

volumes:
  redis-data:
