version: '3'

services:
  redis:
    image: 'redis'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'redis-data:/data'
    command: 'redis-server --save 5 1 --loglevel warning'
    restart: unless-stopped

  python-daemon:
    build: './python-daemon'
    restart: unless-stopped
    environment:
      TP_LINK_EMAIL: ${TP_LINK_EMAIL}
      TP_LINK_PASSWORD: ${TP_LINK_PASSWORD}
      GOODWE_EMAIL: ${GOODWE_EMAIL}
      GOODWE_PASSWORD: ${GOODWE_PASSWORD}

  rboit-back:
    build: './rboit-back'
    environment:
      TZ: 'Europe/Amsterdam'
      PYTHON_DAEMON: 'http://python-daemon/'
      GOVEE_DAEMON: 'http://${PI_HOST}:8069/'
      DTS353F_DAEMON: 'http://${PI_HOST}:8096/'
      REDIS_URL: 'redis://redis/'
      DEVICE_CACHE_MAX_AGE: '900'
      DEVICE_HISTORY_LENGTH: '86400000'  # 24 hours
      DEVICE_HISTORY_INTERVAL: '10000'
      CLIENT_HISTORY_INTERVAL: '1000'
      STORE_HISTORY: 'true'
      DISCORD_ID: ${DISCORD_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      HUE_HUB_ADDRESS: ${HUE_HUB_ADDRESS}
      HUE_USERNAME: ${HUE_USERNAME}
      HUE_CLIENT_KEY: ${HUE_CLIENT_KEY}
    restart: unless-stopped
    ports:
      - '8081:80'

  rboit-front:
    build: './rboit-front'
    ports:
      - '8080:80'
    restart: unless-stopped

volumes:
  redis-data:
