version: '3'

services:
  redis:
    image: 'redis'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'redis-data:/data'
    command: 'redis-server --save 5 1 --loglevel warning'
    restart: unless-stopped

  python-daemon:
    build: './python-daemon'
    env_file: '.env'
    ports:
      - '8082:80'  # Only needed for development
    restart: unless-stopped

  rboit-back:
    build: './rboit-back'
    env_file: '.env'
    environment:
      TZ: 'Europe/Amsterdam'
      PYTHON_DAEMON: 'http://python-daemon/'
      GOVEE_DAEMON: 'http://10.43.60.2:8069/'
      DTS353F_DAEMON: 'http://10.43.60.2:8096/'
      REDIS_URL: 'redis://redis/'
      DEVICE_CACHE_MAX_AGE: '900'
      DEVICE_HISTORY_LENGTH: '86400000'  # 24 hours
      DEVICE_HISTORY_INTERVAL: '10000'
      CLIENT_HISTORY_INTERVAL: '1000'
      STORE_HISTORY: 'true'
    ports:
      - '8081:80'  # Only needed for development
    restart: unless-stopped

  rboit-front:
    build: './rboit-front'
    ports:
      - '8080:80'
    restart: unless-stopped

volumes:
  redis-data:
