version: '3'

services:
  redis:
    image: 'redis'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
    - 'redis-data:/data'
    command: 'redis-server --save 5 1 --loglevel warning'

  python-daemon:
    build: './python-daemon'
    env_file: '.env'
    ports:
    - '8082:80'  # Only needed for development
    devices:
    - '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A10MONL8-if00-port0'
    environment:
      DTS353F_USB_DEVICE: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A10MONL8-if00-port0'
      TP_LINK_EMAIL: ${TP_LINK_EMAIL}
      TP_LINK_PASSWORD: ${TP_LINK_PASSWORD}
      GOODWE_EMAIL: ${GOODWE_EMAIL}
      GOODWE_PASSWORD: ${GOODWE_PASSWORD}

  govee-bluetooth-daemon:
    build: './govee-bluetooth-daemon'
    environment:
      PORT: '8069'
    network_mode: host  # Needed for bluetooth
    privileged: true  # Needed for bluetooth

  rboit-back:
    build: './rboit-back'
    env_file: '.env'
    environment:
      TZ: 'Europe/Amsterdam'
      PYTHON_DAEMON: 'http://python-daemon/'
      GOVEE_DAEMON: 'http://172.17.0.1:8069/'
      REDIS_URL: 'redis://redis/'
      DEVICE_CACHE_MAX_AGE: '900'
      DEVICE_HISTORY_LENGTH: '86400000'  # 24 hours
      DEVICE_HISTORY_INTERVAL: '10000'
      CLIENT_HISTORY_INTERVAL: '1000'
      STORE_HISTORY: 'true'
      DISCORD_ID: ${DISCORD_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      HUE_HUB_ADDRESS: ${HUE_HUB_ADDRESS}
      HUE_USERNAME: ${HUE_USERNAME}
      HUE_CLIENT_KEY: ${HUE_CLIENT_KEY}
    ports:
    - '8081:80'  # Only needed for development

  rboit-front:
    build: './rboit-front'
    ports:
    - '8080:80'

volumes:
  redis-data:
